### PR TITLE
fix: fake mailer assert methods

### PR DESCRIPTION
**Pull request by memsbdm**

### CODE REVIEW

**Comment by RomainLanz** [comment]
Could you please explain your changes?

**Comment by memsbdm** [comment]
@RomainLanz previous methods used in docs (assertHasTo, assertHasFrom, ..) doesn't exist anymore. It should be / was replaced by assertTo, assertFrom, ...

Also these methods are not returning `this` anymore so we cannot chain them so I removed that part from the first example.

**Comment by RomainLanz** [comment]
Cool! I wonder if it wouldn't be better to add back the "chainability" of those assertions.

Let's see what @Julien-R44 or @thetutlage think.

**Comment by thetutlage** [comment]
The PR for docs matches the implementation. We can discuss about chaining of methods separately 🙂

**Comment by thetutlage** [comment]
Thanks @memsbdm

**Pull request merged**
