### PR TITLE
feat: add pagination to doc

### PR DESCRIPTION
**Pull request by prisca-c**
Hello 👋 

This is a PR to solve issue #34 .

I've added an edge global to handle the pagination called `getPagination` and called it inside `docs.edge` within the component pagination.

I'll share some screenshot of what it looks like.

Right now on desktop it looks like this : 
image

When you hover a button it gets a little bit brighter.

The main "issue" here is when text takes a lot of place it looks really tight in mobile : 

Eventually in mobile, text can be align left / right , i can edit it , here's how it looks like : 

Tell me if you've got any suggestions ! 😄

### CODE REVIEW

**Comment by Julien-R44** [comment]
Cool !!

On mobile, the two buttons can probably be stacked. Example on the nuxt doc: image

https://nuxt.com/docs/getting-started/configuration

I think there are a few styling tweaks to be made, but I'll let @thetutlage talk about that first since he designed the website

**Comment by prisca-c** [comment]
Oh it would look better like this, keeping it in mind, waiting for more info and i'll make the changes !

**Comment by RomainLanz** [comment]
This is neat, great job @prisca-c!

I agree with Julien, stacking the block on mobile seems the way to go.

I am not sure if we should reverse the order on mobile; you are more likely to move forward than backward.

**Comment by prisca-c** [comment]
Style Update 🎨 : 

image

image

**Comment by RomainLanz** [comment]
Thanks! 🔥

**Pull request merged**
