### PR TITLE
Update database.md

### PR DESCRIPTION
**Pull request by eduwass**
For the truncate command to work this was needed

See:
https://github.com/orgs/adonisjs/discussions/4609

### CODE REVIEW

**Comment by thetutlage** [comment]
I am not sure this is the right solution. Japa hooks must return the cleanup function and not execute them as it is.

This is how I expect the `truncate` database hook to work

- Before running each test it will migrate the database
- After each test it will truncate the database.

Maybe, you have different expectations. You were expecting the `truncate` method to truncate the database before running the tests.

**Comment by eduwass** [comment]
Hi @thetutlage,  

First of all, thank you for your amazing work and for taking the time to reply! 🙏 

Thanks again for the clarification on how hooks are implemented in Japa. By the way, I found these docs here to be quite useful: https://japa.dev/docs/lifecycle-hooks  

This behavior was initially what confused me, compared to most testing frameworks (like PHPUnit, Jest, or Mocha), where:  
- `setup` runs preparation logic directly **before each test**.  
- `teardown` runs cleanup logic directly **after each test**.  

In this case, I had expected `setup` to allow me to run `await testUtils.db().truncate()` directly without needing to manage a returned function explicitly. Having to "double call" (first to get the function, then to execute it) adds complexity and makes the behavior less predictable, especially for new users like me.  

Would it make sense to:  
1. Simplify `testUtils.db().truncate()` to perform the truncation immediately without returning a separate function?  
2. Or, add clearer documentation about why `truncate` requires this additional step?  

I’d be happy to help refine the documentation to clarify this behavior if needed. 

Thanks for your patience!

**Comment by thetutlage** [comment]
I just looked at the [hook's implementation](https://github.com/adonisjs/lucid/blob/21.x/src/test_utils/database.ts#L45-L48) and it seems the purpose of the hook is to first migrate the database (during the starting of the test) and then truncate the database (at the end of the test). Basically, a single hook to perform both setup and teardown.

Maybe what you are looking for is a standalone hook that has no cleanup function attached to it and then you decide where to call it.

**Comment by thetutlage** [comment]
Closing the PR. We can have a standalone hook in Lucid. But atleast the usage of this hook is demonstrated properly

**Comment by eduwass** [comment]
> I just looked at the [hook's implementation](https://github.com/adonisjs/lucid/blob/21.x/src/test_utils/database.ts#L45-L48) and it seems the purpose of the hook is to first migrate the database (during the starting of the test) and then truncate the database (at the end of the test). Basically, a single hook to perform both setup and teardown.

Got it,

Thanks @thetutlage !

**Pull request closed without merging**
