### PR TITLE
feat: og images

### PR DESCRIPTION
**Pull request by Julien-R44**
Based on #86 - 

Added OG image generation for each documentation page at build-time using an SVG template.

The implementation is a bit hackish: 
  - To extract the summary I capture it in the HTML rather than extracting it from the frontmatter but it seems to me that via dimmer it's currently impossible to extract the frontmatter when I need it.
  - To insert the image in the final `.html`, well, same thing, I `readFile` + `writeFile` the built `.html`. Not so good
 
We need add some hooks for allowing that in Dimmer. In the meantime, it work perfectly, so I don't think there's any hurry

---

The result

image
image
image
image

Let me know if you like the OG template

---

Before merging : 

- [ ] Merge #86 
- [ ] Add `summary` on every page

### CODE REVIEW

**Comment by Julien-R44** [comment]
if you can please give me the cloudflares logs to see why it's failing. but i think it's caused by `sharp`. if that's right, it's not a problem: we'll push the OG image to the repo, it was the initial goal

**Comment by RomainLanz** [comment]
> if you can please give me the cloudflares logs to see why it's failing

The error is about the `package-lock` file being outdated.

```
npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
```

---

Could we make the summary/excerpt be the whole line? It seems cluttered right now.

**Comment by Julien-R44** [comment]
The fonts are correct, they are encoded and inlined as base64 in the svg template

**Comment by thetutlage** [comment]
Seems like you have used pnpm on your local to install dependencies and therefore the `package-lock.json` file is not updated

**Comment by Julien-R44** [comment]
Diff is totally messed up. I will reopen a PR

**Pull request closed without merging**
